# 디스코드 봇 토큰
BotToken: 'Insert Your Bot Token Here'

# 사용할 디스코드 서버
DiscordGuild: 'Insert Server ID Here'

# 인증 후 역할
VerifiedRole: 'Insert Verified Role ID here'

# 디스코드 봇 명령어
CommandPrefix: '학생'
AuthCommand: '!인증'
AuthChannel: 'Input Server Auth Channel ID'

# 디스코드 봇 도움말
HelpMessages:
  - '[PREFIX] 글내려 - 학생이 글을 내릴지도...?'
  - '[PREFIX] 인증 [플레이어] - 디스코드 계정과 해당 플레이어를 연동시킵니다.'

# 인증관련 안내메시지
AuthMessages:
  - ''
  - '&c[&aG&d] &f｜ 디스코드 인증을 위해선 아래의 명령어를 DM으로 전송하세요.'
  - '&c[&aG&d] &f｜ "!인증 [AUTHCODE]"'

# 기타 메시지, \n 사용가능
NotAuthChannel: '```이 명령어는 인증 채널에서만 사용할 수 있습니다.```'
AlreadyAuthed: '```이미 인증을 완료하였습니다.```'
AlreadyAuthing: '```이미 인증을 진행하고 있습니다. DM을 확인해주세요.```'
PlayerOffline: '```해당 플레이어는 현재 오프라인입니다.```'
PlayerAlreadyAuthed: '```해당 플레이어는 이미 인증되었습니다.```'
NotAuthStarted: '```먼저 서버에서 인증절차를 시작해주세요.```'
InputAuthCode: '```인증코드를 입력하세요. !인증 [인증코드]```'

# 다른 유저가 해당 플레이어와 인증을 시도할시 출력메시지, \n, [USER] 사용가능
SomeoneAuthingPlayer: '```해당 플레이어를 대상으로 한 유저가 인증하고 있습니다.```\n해당 유저 : [USER]'

# 인증코드를 3회이상 잘못입력시 출력메시지, \n, [SHOWTIME] 사용가능
CannotAuthNow: '```현재 인증코드를 3회이상 잘못입력하였습니다. \n[COOLTIME]초뒤에 다시 인증하실 수 있습니다.```'

# 인증코드를 잘못입력시 출력메시지, \n, [LEFTCHANCE], [COOLTIME] 사용가능
WrongAuthCode: '```인증코드를 잘못입력했습니다. \n앞으로 [LEFTCHANCE]회 잘못 입력시 [COOLTIME]초 후에 인증을 시도할 수 있습니다.```'

# 인증 명령어에서 플레이어를 입력하지 않았을시, \n, [PREFIX] 사용가능
InputPlayer: '```인증할 플레이어를 입력하세요. \n[PREFIX] [플레이어]```'

# 3번 이상 실패할 경우 인증 쿨타임
AuthCoolTime: 300
